@startuml grid_cells_class

class GridCells {
    - cells: Array<Array<CellWithNeighbors>>
    - num_empties: Integer
    --
    + new(cells: Array<Array<CellWithNeighbors>>)
    + num_empties: Integer
    + reveal_cell(position: position): void
    + toggle_flag(position: position): void
    + count_revealed_cell: Integer
    + bombed?: Boolean
    + width: Integer
    + height: Integer
    + display: void
    - count_empty_cell: Integer
}

@enduml