@startuml grid_cells_creators_hard_class

class GridCellsCreators::Hard {
    --
    {static} WIDTH = 16
    {static} HEIGHT = 16
    {static} NUM_BOMBS = 40
    --
    - create: GridCells
}

@enduml 