@startuml grid_cells_creator_class

class GridCellsCreator {
    {static} NUM_NEIGHBORS: Integer = 8
    {static} DX: Array<Integer>
    {static} DY: Array<Integer>
    {static} WIDTH: Integer = 9
    {static} HEIGHT: Integer = 9
    {static} NUM_BOMBS: Integer = 10
    {static} NUM_CELLS: Integer = WIDTH * HEIGHT
    --
    {static} create: GridCells
    - {static} coordinations(x: Integer, y: Integer): Array<Array<Integer>>
}

@enduml