@startuml minesweeper_class

class Minesweeper {
    - grid_cells: GridCells
    - finished: Boolean
    --
    {static} EASY: Symbol
    {static} NORMAL: Symbol
    {static} HARD: Symbol
    --
    + new(difficulty: Symbol)
    + grid_cells: GridCells
    + reveal_cell(x: Integer, y: Integer): void
    + toggle_flag(x: Integer, y: Integer): void
    + finished?: Boolean
    - check_finish_after_reveal: void
}

@enduml