@startuml Overview

top to bottom direction

skinparam defaultFontName HackGen

skinparam linetype ortho

!include domains/minesweeper_class.plantuml
!include domains/board_class.plantuml
!include domains/grid_cells_creator_class.plantuml
!include domains/grid_cells_class.plantuml
!include domains/cell_with_neighbors_class.plantuml
!include domains/position_class.plantuml
!include domains/cell_class.plantuml

!include domains/grid_cells_interface.plantuml
!include domains/neighbor_interface.plantuml
!include domains/position_interface.plantuml
!include domains/base_interface.plantuml

Minesweeper --> Board
Minesweeper --> GridCellsCreator
Minesweeper --> Position

Board --> grid_cells
Board --> position
Board .d[hidden].> GridCells

GridCellsCreator --> Cell
GridCellsCreator "生成" --> CellWithNeighbors

GridCells -r-> position
GridCells .l[hidden].> grid_cells

grid_cells --> position

Position .l[hidden].> position

CellWithNeighbors --> base
CellWithNeighbors -r-> neighbor
CellWithNeighbors .d[hidden].> Cell

Cell .r[hidden].> base

@enduml