@startuml overview_minesweeper

top to bottom direction

skinparam defaultFontName HackGen

skinparam linetype ortho

!include minesweeper_class.plantuml
!include board_class.plantuml
!include grid_cells_class.plantuml
!include position_class.plantuml
!include grid_cells_factory_class.plantuml

!include grid_cells_interface.plantuml
!include position_interface.plantuml

Minesweeper --> Board
Minesweeper --> Position

Board --> grid_cells
Board --> position
Board --> GridCellsFactory

GridCellsFactory --> GridCells

GridCells ..|> grid_cells
GridCells --> position

grid_cells --> position

Position ..|> position

@enduml