@startuml Overview

top to bottom direction

skinparam defaultFontName HackGen

skinparam linetype ortho

!include minesweeper_class.plantuml
!include board_class.plantuml
!include grid_cells_creator_class.plantuml
!include grid_cells_class.plantuml
!include cell_with_neighbors_class.plantuml
!include position_class.plantuml
!include cell_class.plantuml

!include grid_cells_interface.plantuml
!include neighbor_interface.plantuml
!include position_interface.plantuml
!include base_interface.plantuml

Minesweeper --> Board
Minesweeper --> GridCellsCreator
Minesweeper --> Position

Board --> grid_cells
Board --> position
Board .d[hidden].> GridCells

GridCellsCreator --> Cell
GridCellsCreator "生成" --> CellWithNeighbors

GridCells -r-> position
GridCells .l[hidden].> grid_cells

grid_cells --> position

Position .l[hidden].> position

CellWithNeighbors --> base
CellWithNeighbors -r-> neighbor
CellWithNeighbors .d[hidden].> Cell

Cell .r[hidden].> base

@enduml