@startuml Board Class

class Board {
    - grid_cells: GridCells
    --
    + new(grid_cells: grid_ells)
    + reveal_cell(position: position): void
    + toggle_flag(position: position): void
    + count_revealed_cell: Integer
    + bombed?: Boolean
    + num_empties: Integer
    + display: void
}

@enduml