name: Generate PlantUML images

on:
  push:
    branches: [ main ]
    # paths:
    #   - 'diagrams/**/*.plantuml'
permissions:
  contents: write 
jobs:
  generate-images:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml
      - name: Generate UML diagrams
        run: |
          plantuml -tpng -charset UTF-8 diagrams/**/*.plantuml -o ../images
      - name: Commit diagram images
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add images
            git commit -m "Update UML diagrams"
            git push
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
