name: Steep

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          cache-bundler: true

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run Steep
        run: bundle exec steep check
